# Netlify Configuration File

[build]
  command = "npm run build"  # Change this based on your build command
  publish = "dist"  # Change this to your build output directory (e.g., "build" for React, "dist" for Vue)

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment Variables (Optional)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Custom Headers (Optional)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
